GewichtIngave/Models/ErrorViewModel.cs
using System;

namespace GewichtIngave.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GewichtIngave/Models/GewichtModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GewichtIngave.Models
{
    public class GewichtModel
    {
        public int Id { get; set; }
        public DateTime Datum { get; set; }
        public int Gewicht { get; set; }
        public string Comment { get; set; }
    }
}

GewichtIngave/Controllers/GewichtController.cs
using GewichtIngave.Data;
using GewichtIngave.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GewichtIngave.Controllers
{
    public class GewichtController : Controller
    {
        GewichtDbContext Context;
        public GewichtController(GewichtDbContext context)
        {
            Context = context;
        }
        public IActionResult Index()
        {
            return View(Context.Wegingen);
        }
        public IActionResult Detail(int id)
        {
            var gewicht = Context.Wegingen.Where(a => a.Id == id);
            return View(gewicht.FirstOrDefault());
        }
        public IActionResult AddGewicht()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddGewicht(GewichtModel Wage)
        {
            if (ModelState.IsValid)
            {
                Context.Wegingen.Add(Wage);
                Context.SaveChanges();
                int id = Wage.Id;
                return RedirectToAction("Detail", new { id = Wage.Id });
            }
            return View(Wage);
        }
    }
}

GewichtIngave/Controllers/HomeController.cs
using GewichtIngave.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GewichtIngave.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Landigspagina";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GewichtIngave/Views/Gewicht/AddGewicht.cshtml
@model GewichtModel

<h1>Nieuw gewicht ingeven</h1>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>Gewicht</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gewicht, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gewicht, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gewicht, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Voeg gewicht toe" class="btn btn-default" />
            </div>
        </div>
    </div>
}

GewichtIngave/Views/Gewicht/Detail.cshtml
@model GewichtModel

<h1>@Model.Datum</h1>
<H2>@Model.Gewicht kg</H2>
<p>@Model.Comment</p>

GewichtIngave/Views/Gewicht/Index.cshtml
@model IEnumerable<GewichtModel>

<table>
    <tr>
        <th>Datum</th>
        <th>Gewicht</th>
        <th>Comment</th>
    </tr>
    @foreach (GewichtModel GewichtModel in Model)
    {
        <tr>
            <td>@GewichtModel.Datum</td>
            <td>@GewichtModel.Gewicht kg</td>
            <td>@GewichtModel.Comment</td>
            <td>@Html.ActionLink("Go to Details", "Detail", "Gewicht", new { id = GewichtModel.Id }, new { @class = "btn btn-primary" })</td>
        </tr>
    }
</table>
@Html.ActionLink("voeg gewicht toe", "AddGewicht", "Gewicht", null, new { @class = "btn btn-primary" })

GewichtIngave/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GewichtIngave/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GewichtIngave</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GewichtIngave</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gewicht" asp-action="Index">Gewicht ingave</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GewichtIngave - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>